[package]

name = "pistoncore-glutin_window"
version = "0.9.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["glutin", "window", "piston"]
description = "A Piston window back-end using the Glutin library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glutin_window.git"
homepage = "https://github.com/pistondevelopers/glutin_window"

[lib]

name = "glutin_window"
path = "src/lib.rs"

[dependencies]
gl = "0.0.12"
glutin = "0.3.4"
pistoncore-input = "0.4.0"
pistoncore-window = "0.6.0"
shader_version = "0.2.0"

