[package]

name = "pistoncore-glutin_window"
version = "0.21.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["glutin", "window", "piston"]
description = "A Piston window back-end using the Glutin library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glutin_window.git"
homepage = "https://github.com/pistondevelopers/glutin_window"

[lib]

name = "glutin_window"
path = "src/lib.rs"

[dependencies]
gl = "0.5.2"
glutin = "0.4.2"
pistoncore-input = "0.8.0"
pistoncore-window = "0.15.0"
shader_version = "0.2.1"
