[package]

name = "pistoncore-glutin_window"
version = "0.49.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["glutin", "window", "piston"]
description = "A Piston window back-end using the Glutin library"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/glutin_window.git"
homepage = "https://github.com/pistondevelopers/glutin_window"

[lib]
name = "glutin_window"
path = "src/lib.rs"

[dependencies]
gl = "0.10.0"
glutin = "0.18.0"
pistoncore-input = "0.22.0"
pistoncore-window = "0.33.0"
shader_version = "0.3.0"
